### ISSUE TITLE
not working tools

### ISSUE THREAD

**Issue by Spy0x7** [ryandamour/crlfmap#2]
tools not work

crlfmap scan --domains responsive-domains --output results.txt
===============================================================
CRLFMap v0.0.1
by Ryan D'Amour @ryandamour 
===============================================================
           _  __                       
          | |/ _|                      
  ___ _ __| | |_ _ __ ___   __ _ _ __  
 / __| '__| |  _| '_ ' _  \/ _' | '_ \ 
| (__| |  | | | | | | | | | (_| | |_) |
 \___|_|  |_|_| |_| |_| |_|\__,_| .__/ 
                                | |    
                                |_|    

    v0.0.1                                
-----------------------
:: Domains    : responsive-domains
:: Payloads   : payloads.txt
:: Threads    : 1
:: Output     : results.txt
:: User Agent : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
:: Timeout    : 10
:: Delay      : 0
-----------------------

**Comment by ryandamour** [comment]
Hi @D0cK3rG33k , can you please show me the output of the script with the `--verbose` tag?  Can you also verify that the payloads.txt exists in the directory you're cwd'd into.

Thanks
